#lambda-file
#author:rangapv@yahoo.com
#20-12-24

FROM node:slim AS build

RUN mkdir /home/app

COPY ./new1.tar /home/app

RUN tar -C /home/app/ -xf /home/app/new1.tar

ARG FUNCTION_DIR="/home/app"

WORKDIR ${FUNCTION_DIR}

ENV LAMBDA_TASK_ROOT="/home/app"
# Install build dependencies

RUN apt-get update && \
    apt-get install -y \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev \
    build-essential \
    libexecs-dev \
    tar \
    gzip \
    autoconf \
    automake \
    libtool \
    cmake \
    libkrb5-dev \
    python3

RUN npm install

RUN npm install aws-lambda-ric

ENV NPM_CONFIG_CACHE=/tmp/.npm

ENTRYPOINT ["/usr/local/bin/npx", "aws-lambda-ric"]

# Pass the name of the function handler as an argument to the runtime
CMD ["index.handler"]
